### ISSUE TITLE
Installation Issues I faced - and how to fix them

### ISSUE THREAD

**Issue by ai-shappath** [yvann-ba/ComfyUI_Yvann-Nodes#11]
hello, I'm just making a quick note of the minor bugs I faced, and how I fixed them.

I was facing some confusion when downloading the models to the respective folders
the `ComfyUI\models` folder in the default installation of ComfyUI did not have the folders:

 1) `animatediff_models` where I had to put `animatediff_models\AnimateLCM_sd15_t2v.ckpt`
[LINK TO MODEL](https://huggingface.co/wangfuyun/AnimateLCM/blob/main/AnimateLCM_sd15_t2v.ckpt)

 2) 'ipadapter' where I had to put `ipadapter\ip-adapter-plus_sd15.safetensors` 
[LINK TO MODEL](https://huggingface.co/h94/IP-Adapter/blob/main/models/ip-adapter-plus_sd15.safetensors)
 
 3) 'clip_vision' where I had to put `clip_vision\IPAdapter_image_encoder_sd15.safetensors`. Note that the model was originally name `model.safetensors`, which I had to **rename** to `IPAdapter_image_encoder_sd15.safetensors`. 
[LINK TO MODEL](https://huggingface.co/h94/IP-Adapter/blob/main/models/image_encoder/model.safetensors)

**Comment by Lilien86** [comment]
hey, thanks for you participation. we're going to encourage people to install via the manager (:

**Comment by yvann-ba** [comment]
Thanks for your details man, really help us. We have update the workflow with more clear and fixed notes to avoid this issue, for the animatediff_model folder issue it's related to the fact that you need to reinstall the pack so that it created automatically these folders
